### ISSUE TITLE
Powwow is missing UTF-8 support

### ISSUE THREAD

**Issue by nschimme** [MUME/powwow#1]
Right now `cha charset utf-8` doesn't work in MUME

**Comment by nschimme** [comment]
I've narrowed it down to this line but even forcing `en_US-UTF-8` doesn't work:
https://github.com/MUME/powwow/blob/master/tty.c#L855

Perhaps @gustavh can figure it out since it looks like he's the original author.

**Comment by gustavh** [comment]
The current powwow design is to always have ISO-8859-1 in memory as well on
the network so that would all have to rewritten.
The code in tty.c is only dealing with the local terminal.

It seems like a lot of work to support a new network encoding. You can
support that RFC without adding any new encoding, right?

**Comment by nschimme** [comment]
Seeing as how MUME doesn't even support UTF-8 internally I'm going to close this issue.
